### ISSUE TITLE
[FEATURE] Export BrowserSentryClientOptions from micro-sentry library

### ISSUE THREAD

**Issue by alxpsr** [taiga-family/micro-sentry#16]
# 🚀 Feature request

### Is your feature request related to a problem?
At the moment you can use only `MicroSentryErrorHandler` class for ErrorHandler implementation without any additional preparations. And it makes sense if your app uses only 1 ErrorHandler which is good and by Angular design. I faced with situation when the App uses multiple ErrorHandler in conjunction with kind of Visitor pattern. So i could not just use your MicroSentryErrorHandler and i had to use `MicroSentryService` directly. But then i had to declare `MICRO_SENTRY_CONFIG` token which has `MicroSentryModuleOptions` type that you don't export from lib. Of course i could use `any` type but i wanted more type-safety feature.

### Describe the solution you'd like
Export `BrowserSentryClientOptions` type from lib for more flexibility purposes

### Additional context
Who faced with such issue you can use workaround:

```ts
import { MicroSentryService } from '@micro-sentry/angular';

type MicroSentryModuleOptionsParams = ConstructorParameters<typeof MicroSentryService>;
type FirstElemFromTuple<T extends unknown[]> = T extends [infer R, unknown] ? R : never;
export type MicroSentryModuleOptions = FirstElemFromTuple<MicroSentryModuleOptionsParams>;
```

Then you will get `BrowserSentryClientOptions` type

**Comment by sevaru** [comment]
Hi there,

Great point! 
As a slightly easier workaround, you can import the type directly from the `@micro-sentry/browser` package:

```ts
import { BrowserSentryClientOptions } from '@micro-sentry/browser';
```

But this could possibly have some linting issues, depending on your setup (like no-extraneous-dependencies).

So your idea to reexporting sounds good.
And it would be more user-friendly too.

Thanks for this suggestion!

**Comment by sevaru** [comment]
After further investigation into this issue, we consider importing directly from `@micro-sentry/browser` as a suitable solution. 
Reexporting would require not only the options type but also the types for its properties and more, making it a bit complex.

```ts
import { BrowserSentryClientOptions } from '@micro-sentry/browser';
```

Looking ahead, we're thinking about moving the dependency on `@micro-sentry/browser` to peer dependencies, making the current workaround a future-proof approach.

I'm closing this issue for now, but feel free to reopen if you have any other questions or concerns!
